# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: recommendations.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15recommendations.proto\x12\x10\x63om.ivchern.grpc\"Y\n\x0b\x43\x61rdRequest\x12\n\n\x02id\x18\x01 \x01(\x03\x12\r\n\x05skill\x18\x02 \x03(\t\x12/\n\x0bmatchedCard\x18\x03 \x03(\x0b\x32\x1a.com.ivchern.grpc.CardList\"%\n\x08\x43\x61rdList\x12\n\n\x02id\x18\x01 \x01(\x03\x12\r\n\x05skill\x18\x02 \x03(\t\"&\n\x0c\x43\x61rdResponse\x12\x16\n\x0eselectedCardId\x18\x01 \x03(\x03\x32g\n\x14recommendationSystem\x12O\n\x0erecommendation\x12\x1d.com.ivchern.grpc.CardRequest\x1a\x1e.com.ivchern.grpc.CardResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'recommendations_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_CARDREQUEST']._serialized_start=43
  _globals['_CARDREQUEST']._serialized_end=132
  _globals['_CARDLIST']._serialized_start=134
  _globals['_CARDLIST']._serialized_end=171
  _globals['_CARDRESPONSE']._serialized_start=173
  _globals['_CARDRESPONSE']._serialized_end=211
  _globals['_RECOMMENDATIONSYSTEM']._serialized_start=213
  _globals['_RECOMMENDATIONSYSTEM']._serialized_end=316
# @@protoc_insertion_point(module_scope)
