# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import protobufs.recommendations_pb2 as recommendations__pb2


class recommendationSystemStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.recommendation = channel.unary_unary(
                '/com.ivchern.grpc.recommendationSystem/recommendation',
                request_serializer=recommendations__pb2.CardRequest.SerializeToString,
                response_deserializer=recommendations__pb2.CardResponse.FromString,
                )


class recommendationSystemServicer(object):
    """Missing associated documentation comment in .proto file."""

    def recommendation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_recommendationSystemServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'recommendation': grpc.unary_unary_rpc_method_handler(
                    servicer.recommendation,
                    request_deserializer=recommendations__pb2.CardRequest.FromString,
                    response_serializer=recommendations__pb2.CardResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.ivchern.grpc.recommendationSystem', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class recommendationSystem(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def recommendation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.ivchern.grpc.recommendationSystem/recommendation',
            recommendations__pb2.CardRequest.SerializeToString,
            recommendations__pb2.CardResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
